---
title: Hex stickers
subtitle: Gallery with hexagon layout
date: last-modified
date-format: "DD-MMM-YYYY"
format:
  html:
    page-layout: full
    toc: false
---

A gallery displaying the hex stickers from [Posit](https://github.com/rstudio/hex-stickers).

```{r}
#| code-fold: true
url <- "https://raw.githubusercontent.com/rstudio/hex-stickers/refs/heads/main/SVG/"
svgs <- c(
  "R6",
  "RStudio",
  "agua",
  "air",
  "applicable",
  "ark",
  "baguette",
  "blastula",
  "blogdown",
  "bonsai",
  "bookdown",
  "broom",
  "bslib",
  "butcher",
  "censored",
  "chattr",
  "chromote",
  "clock",
  "connectapi",
  "connections",
  "corrr",
  "covr",
  "dbplot",
  "dbplyr",
  "devtools",
  "dials",
  "discrim",
  "distill",
  "dplyr",
  "dsbox",
  "dtplyr",
  "duckplyr",
  "ellmer",
  "embed",
  "farver",
  "feather",
  "filtro",
  "finetune",
  "flexdashboard",
  "forcats",
  "fs",
  "furrr",
  "gganimate",
  "ggplot2",
  "glue",
  "googledrive",
  "googlesheets",
  "googlesheets4",
  "great_tables",
  "gt",
  "gtable",
  "hardhat",
  "haven",
  "hms",
  "htmltools",
  "httr2",
  "infer",
  "keras3",
  "knitr",
  "lintr",
  "lobstr",
  "lubridate",
  "luz",
  "mall",
  "marquee",
  "miniCRAN",
  "modeldb",
  "modelr",
  "multilevelmod",
  "odbc",
  "orbital",
  "pagedown",
  "parsnip",
  "patchwork",
  "pins",
  "pipe",
  "pkgdown",
  "plotnine",
  "plumber",
  "plumber2",
  "plumbertableau",
  "pointblank",
  "poissonreg",
  "positron",
  "probably",
  "promises",
  "purrr",
  "quarto",
  "r2d3",
  "ragg",
  "rapp",
  "reactlog",
  "readr",
  "readxl",
  "recipes",
  "renv",
  "reprex",
  "reticulate",
  "rlang",
  "rmarkdown",
  "roxygen2",
  "rray",
  "rrd",
  "rsample",
  "rsconnect",
  "rstudioapi",
  "rticles",
  "rules",
  "rvest",
  "rwasm",
  "sass",
  "scales",
  "shiny",
  "shinychat",
  "shinytest2",
  "siuba",
  "sloop",
  "sortable",
  "sparklyr",
  "sparsevctrs",
  "spatialsample",
  "sss",
  "stacks",
  "stringr",
  "svglite",
  "systemfonts",
  "tensorflow",
  "testthat",
  "textrecipes",
  "themis",
  "tibble",
  "tidyclust",
  "tidymodels",
  "tidyposterior",
  "tidypredict",
  "tidyr",
  "tidyverse",
  "torch",
  "tune",
  "usethis",
  "vctrs",
  "vetiver",
  "webr",
  "withr",
  "workflows",
  "xaringan",
  "yardstick"
)
paths <- paste0(url, svgs, ".svg")
```

```{r}
library(pixture)
pixgallery(paths, layout = "hexagon", h = "100px")
```
